### PR TITLE
Reverse of string using C and Bubble Sort in c

### PR DESCRIPTION
**Pull request by prm1999**

### CODE REVIEW

**Comment by Nihal-Priyadarshi** [comment]
Good Work, But Make It Impressive By Using Colon In printf Statement And Capitalize Your All Output Statement, Also Do It Fast As Hacktoberfest Is Ending Soon.

**Comment by prm1999** [comment]
> Good Work, But Make It Impressive By Using Colon In printf Statement And Capitalize Your All Output Statement, Also Do It Fast As Hacktoberfest Is Ending Soon.

i had done upgrade

**Comment by prm1999** [comment]
Thanks for merging PR 
label the PR as hacktoberfest-accepted

**Comment by Nihal-Priyadarshi** [comment]
> Thanks for merging PR
> label the PR as hacktoberfest-accepted

It's ok, you can create as many pull request as you want.

**Pull request merged**
